CREATE TABLE APP_USER (
     id INT AUTO_INCREMENT PRIMARY KEY,
     login VARCHAR(255) NOT NULL UNIQUE,
     password VARCHAR(255) NOT NULL,
     name VARCHAR(255),
     surname VARCHAR(255),
     email VARCHAR(255),
     user_role VARCHAR(255) NOT NULL
);

CREATE TABLE LOCATION (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    address VARCHAR(255) NOT NULL
);

CREATE TABLE USER_LOCATION (
    id INT AUTO_INCREMENT PRIMARY KEY,
    user_id INT REFERENCES APP_USER,
    location_id INT REFERENCES LOCATION,
    permission VARCHAR(255) NOT NULL
);
